# Generated by Django 6.1.1 on 2026-09-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'Por hacer'), ('IN_PROGRESS', 'En proceso'), ('BLOCKED', 'Pendiente'), ('DONE', 'Completado')], default='TODO', max_length=20)),
                ('importance', models.PositiveSmallIntegerField(default=2)),
                ('urgency', models.PositiveSmallIntegerField(default=2)),
                ('base_priority_score', models.PositiveSmallIntegerField(default=4)),
                ('effective_priority_score', models.PositiveSmallIntegerField(default=4)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, choices=[('WAITING_RESPONSE', 'Esperando respuesta'), ('DEPENDENCY', 'Dependo de otra persona'), ('MISSING_INFORMATION', 'Falta información'), ('MISSING_BUDGET', 'Falta presupuesto'), ('RESCHEDULED', 'Reprogramada'), ('TECHNICAL_PROBLEM', 'Problema técnico'), ('OTHER', 'Otro')], default='', max_length=30)),
                ('block_reason_detail', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scopes.scope')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_priority_score', 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Tarea creada'), ('TITLE_CHANGED', 'Título modificado'), ('DESCRIPTION_CHANGED', 'Descripción modificada'), ('STATUS_CHANGED', 'Estado modificado'), ('PRIORITY_CHANGED', 'Prioridad modificada'), ('SCOPE_CHANGED', 'Ámbito modificado'), ('DUE_DATE_CHANGED', 'Fecha límite modificada'), ('TASK_BLOCKED', 'Tarea bloqueada'), ('TASK_UNBLOCKED', 'Tarea desbloqueada'), ('CHECKLIST_UPDATED', 'Checklist actualizado'), ('TASK_COMPLETED', 'Tarea completada'), ('TASK_REOPENED', 'Tarea reabierta'), ('TASK_ARCHIVED', 'Tarea archivada')], max_length=30)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
